version: '3.8'

services:
  core:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
      - DEBUG=true
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./jarvis.db
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # TODO: Add PostgreSQL for production
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: jarvis
  #     POSTGRES_USER: jarvis
  #     POSTGRES_PASSWORD: jarvis
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  redis_data:
  # postgres_data:
